FROM public.ecr.aws/lambda/python:3.12

# Install system deps
RUN microdnf install -y \
        gcc \
        gcc-c++ \
        make \
        geos-devel \
        proj \
        proj-devel \
        mesa-libGLU \
        libXrender \
        libXext \
        freetype-devel \
        libpng-devel \
    && microdnf clean all

# Copy requirements
COPY requirements.txt .

# Install Python deps (NO --target!)
RUN pip install --upgrade pip setuptools wheel \
    && pip install -r requirements.txt

# Copy code into Lambda task root
COPY lambda_function.py zip_utils.py ${LAMBDA_TASK_ROOT}

# Lambda handler
CMD ["lambda_function.lambda_handler"]
